kind: ExternalService
name: reminder
spec:
  env:
    - name: VERSION
      value: ${RELEASE_VERSION}
    - name: MONGO_URI
      secret: mongo-uri
    - name: BOT_TOKEN
      secret: bot-token
  allow_http: true
  image: ${IMAGE_URL}:${TAG}
  image_pull_policy: IfNotPresent
  path: /
  replicas: 1
  resources:
    memory: 200Mi