name: Deploy
on:
    push:
      tags:
        - v*
      branches:
        - main
        - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install fandogh
        run: |
          pip install fandogh-cli --upgrade

      - name: Deploy
        run: |
          chmod +x ./deploy/fandogh/workflow/entry.sh
          username=${{ secrets.FANDOGH_USERNAME }}
          password=${{ secrets.FANDOGH_PASSWORD }}
          image_version=${{ env.RELEASE_VERSION }}
          ./deploy/fandogh/entry.sh $username $password $image_version